spring:
  application:
    name: parking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/parking_db
    username: parking_user
    password: parking_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_yzwNALI2A

logging:
  level:
    root: INFO
    com.pucetec.exam2: DEBUG