spring:
  application:
    name: parking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/exam2
    username: exam2
    password: exam2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_yzwNALI2A

logging:
  level:
    root: INFO
    com.pucetec.exam2: DEBUG
